import type { AdministratorCredentialsRequest, AdministratorSummary, ChangeAdministratorPasswordRequest, ListAdministratorsResponse } from "@ariad/contracts";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";

import { adminTokenStorageKey, administratorIDStorageKey, adminUnauthorizedEvent, getJSON, sendJSON } from "../api";

export function AdministratorsPage() {
  const queryClient = useQueryClient();
  const currentAdministratorID = sessionStorage.getItem(administratorIDStorageKey);
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
	const [currentPassword, setCurrentPassword] = useState("");
	const [newPassword, setNewPassword] = useState("");
  const [created, setCreated] = useState<AdministratorSummary | null>(null);
	const administratorsQuery = useQuery({ queryKey: ["administrators"], queryFn: () => getJSON<ListAdministratorsResponse>("/api/v1/admin/accounts") });
	const mutation = useMutation({ mutationFn: (body: AdministratorCredentialsRequest) => sendJSON<AdministratorCredentialsRequest, AdministratorSummary>("/api/v1/admin/accounts", "POST", body), onSuccess: (administrator) => { setCreated(administrator); setUsername(""); setPassword(""); void queryClient.invalidateQueries({ queryKey: ["administrators"] }); } });
	const deleteMutation = useMutation({ mutationFn: (administratorID: string) => sendJSON<never, { deleted: boolean }>(`/api/v1/admin/accounts/${encodeURIComponent(administratorID)}`, "DELETE"), onSuccess: () => void queryClient.invalidateQueries({ queryKey: ["administrators"] }) });
	const passwordMutation = useMutation({ mutationFn: (body: ChangeAdministratorPasswordRequest) => sendJSON<ChangeAdministratorPasswordRequest, { password_changed: boolean }>("/api/v1/admin/password", "POST", body), onSuccess: () => { sessionStorage.removeItem(adminTokenStorageKey); sessionStorage.removeItem(administratorIDStorageKey); window.dispatchEvent(new Event(adminUnauthorizedEvent)); } });
	return <section className="model-config-page"><div className="eyebrow">Workspace / Settings</div><h1>Administrators</h1><p className="lede">Create a separate account for each person who manages Ariad.</p>{administratorsQuery.isPending ? <p className="empty-state">Loading administrators…</p> : <div className="conversation-list">{administratorsQuery.data?.administrators.map((administrator) => <div className="conversation-row" key={administrator.administrator_id}><strong>{administrator.username}{administrator.administrator_id === currentAdministratorID ? " (you)" : ""}</strong><button type="button" disabled={administrator.administrator_id === currentAdministratorID || deleteMutation.isPending} onClick={() => deleteMutation.mutate(administrator.administrator_id)}>Delete</button></div>)}</div>}<form className="model-config-form" onSubmit={(event) => { event.preventDefault(); setCreated(null); mutation.mutate({ username, password }); }}><h2>Create administrator</h2><label htmlFor="new-admin-username">Username</label><input id="new-admin-username" autoComplete="off" required value={username} onChange={(event) => setUsername(event.target.value)} /><label htmlFor="new-admin-password">Initial password</label><input id="new-admin-password" type="password" minLength={12} autoComplete="new-password" required value={password} onChange={(event) => setPassword(event.target.value)} /><button type="submit" disabled={mutation.isPending}>{mutation.isPending ? "Creating…" : "Create administrator"}</button></form>{created && <p className="notice success">Administrator {created.username} created.</p>}<form className="model-config-form" onSubmit={(event) => { event.preventDefault(); passwordMutation.mutate({ current_password: currentPassword, new_password: newPassword }); }}><h2>Change my password</h2><label htmlFor="current-admin-password">Current password</label><input id="current-admin-password" type="password" autoComplete="current-password" required value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} /><label htmlFor="changed-admin-password">New password</label><input id="changed-admin-password" type="password" minLength={12} autoComplete="new-password" required value={newPassword} onChange={(event) => setNewPassword(event.target.value)} /><button type="submit" disabled={passwordMutation.isPending}>Change password and sign out</button></form>{(mutation.error || deleteMutation.error || passwordMutation.error || administratorsQuery.error) && <p className="notice error">{(mutation.error ?? deleteMutation.error ?? passwordMutation.error ?? administratorsQuery.error)?.message}</p>}</section>;
}
